-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  customer_mobile text,
  customer_address text,
  customer_email text,
  items jsonb, -- Stores array of items {name, quantity, price}
  total_amount numeric,
  status text default 'pending' -- pending, completed, etc.
);

-- Policies for Orders
create policy "Public Select" on public.orders for select using (true);
create policy "Anon Insert" on public.orders for insert with check (true);
create policy "Anon Update" on public.orders for update using (true);
create policy "Anon Delete" on public.orders for delete using (true);
