
-- Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  image text,
  badge text,
  materials text[],
  tagline text,
  description text,
  category_id bigint references public.categories(id)
);

-- Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  image text
);

-- Site Settings Table
create table public.site_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  background_url text,
  hero_text text,
  sub_text text
);

-- Storage Buckets (Execute in SQL Editor if buckets don't exist, though typically done via UI)
-- insert into storage.buckets (id, name) values ('product-images', 'product-images');
-- insert into storage.buckets (id, name) values ('category-images', 'category-images');

-- Policies (Basic public read, anon insert/update for demo)
create policy "Public Access" on public.products for select using (true);
create policy "Anon Insert" on public.products for insert with check (true);
create policy "Anon Update" on public.products for update using (true);
create policy "Anon Delete" on public.products for delete using (true);

create policy "Public Access" on public.categories for select using (true);
create policy "Anon Insert" on public.categories for insert with check (true);
create policy "Anon Update" on public.categories for update using (true);

create policy "Public Access" on public.site_settings for select using (true);
create policy "Anon Insert" on public.site_settings for insert with check (true);
create policy "Anon Update" on public.site_settings for update using (true);
