-- Enable RLS (Safe to re-run) - Essential for policies to work
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- ==========================================
-- 1. Categories Table
-- ==========================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  image text
);

-- ==========================================
-- 2. Products Table
-- ==========================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  category_id bigint references public.categories(id)
);

-- Safe Column Additions for Products (Idempotent)
do $$ 
begin
    -- Original Price
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'original_price') then
        alter table public.products add column original_price numeric;
    end if;
    -- Image (Legacy single)
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'image') then
        alter table public.products add column image text;
    end if;
    -- Images (Multiple)
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'images') then
        alter table public.products add column images text[];
    end if;
    -- Badge (e.g., "New", "Sale")
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'badge') then
        alter table public.products add column badge text;
    end if;
    -- Materials
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'materials') then
        alter table public.products add column materials text[];
    end if;
    -- Tagline
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'tagline') then
        alter table public.products add column tagline text;
    end if;
    -- Description
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'description') then
        alter table public.products add column description text;
    end if;
    -- Variants (JSONB for generic variants like Size, Color) -> New Feature
    if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'variants') then
        alter table public.products add column variants jsonb;
    end if;
end $$;

-- ==========================================
-- 3. Site Settings Table
-- ==========================================
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  background_url text,
  hero_text text,
  sub_text text
);

-- ==========================================
-- 4. Orders Table
-- ==========================================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  customer_mobile text,
  customer_address text,
  items jsonb, -- Stores cart items including selected variants
  total_amount numeric,
  status text default 'completed'
);

-- ==========================================
-- 5. Row Level Security (RLS) Policies
-- ==========================================

-- A. Drop existing policies to prevent "Already Exists" errors
do $$ 
begin
    -- Products
    execute 'drop policy if exists "Public Read Products" on public.products';
    execute 'drop policy if exists "Anon Write Products" on public.products';
    execute 'drop policy if exists "Public Access" on public.products';
    execute 'drop policy if exists "Anon Insert" on public.products';
    execute 'drop policy if exists "Anon Update" on public.products';
    execute 'drop policy if exists "Anon Delete" on public.products';

    -- Categories
    execute 'drop policy if exists "Public Read Categories" on public.categories';
    execute 'drop policy if exists "Anon Write Categories" on public.categories';
    execute 'drop policy if exists "Public Access" on public.categories'; 
    execute 'drop policy if exists "Anon Insert" on public.categories'; 
    execute 'drop policy if exists "Anon Update" on public.categories'; 

    -- Site Settings
    execute 'drop policy if exists "Public Read Settings" on public.site_settings';
    execute 'drop policy if exists "Anon Write Settings" on public.site_settings';
    execute 'drop policy if exists "Public Access" on public.site_settings'; 
    execute 'drop policy if exists "Anon Insert" on public.site_settings'; 
    execute 'drop policy if exists "Anon Update" on public.site_settings'; 

    -- Orders
    execute 'drop policy if exists "Public Read Orders" on public.orders';
    execute 'drop policy if exists "Anon Write Orders" on public.orders';
end $$;

-- B. Enable RLS on all tables
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.site_settings enable row level security;
alter table public.orders enable row level security;

-- C. Create permissive policies (for current Admin usage)
-- Products
create policy "Public Read Products" on public.products for select using (true);
create policy "Anon Write Products" on public.products for all using (true) with check (true);

-- Categories
create policy "Public Read Categories" on public.categories for select using (true);
create policy "Anon Write Categories" on public.categories for all using (true) with check (true);

-- Site Settings
create policy "Public Read Settings" on public.site_settings for select using (true);
create policy "Anon Write Settings" on public.site_settings for all using (true) with check (true);

-- Orders
create policy "Public Read Orders" on public.orders for select using (true);
create policy "Anon Write Orders" on public.orders for all using (true) with check (true);

-- Verify bucket for images (Optional, can be done in UI)
-- insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict do nothing;

-- Add source column to identify POS vs Web orders
ALTER TABLE orders ADD COLUMN IF NOT EXISTS source text DEFAULT 'web';
